### ISSUE TITLE
OpenGL with GPU acceleration?

### ISSUE THREAD

**Issue by soldierofhell** [twobombs/deploy-nvidia-docker#8]
Hi, it's not explicitly stated, but does your nvidia image is supposed to have OpenGL with GPU acceleration (e.g. glxinfo -B shows this)? If so, could you please point me which steps "do the trick"? I was hoping creating my own image with xfce+xrdp based on cudagl image that it's enough to set [Driver Capabilities](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities) to _all_ (because _graphics_ is not in defaults), but seems it's not enough. Unfortunately I can't make your container working (can't even log into VNC) and wonder if it's worth to struggle digging why. Thanks,

Regards,

**Comment by twobombs** [comment]
Welcome, this image forms a minimal multiarch basis for further use in middleware- and application container images

As a standalone image there isn't a whole lot of platform specific acceleration support included because those are 
often hardware specific and this image needs to be as vanilla as it comes and able to run on a wide variety of hardware platforms

exposing OpenGL in a container can be done by either using Zink ( Vulkan to OpenGL ) a beta feature integrated into cudacluster:vulcan  [https://github.com/twobombs/cudacluster]( https://github.com/twobombs/cudacluster) the middle ware that adds a lot of specific acceleration to this image

or by mapping the Hosts' X socket into the container at runtime thus ( also )  layering the container app unto the desktop

an example how that would work looks like ( also with screenshots ) 
docker run --gpus all -d -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -p 6080:6080 -v /run/user/1000/gdm/Xauthority:/root/.Xauthority -h $HOSTNAME twobombs/thereminq-bonsai

[https://github.com/twobombs/thereminq-bonsai#deploy-bonsai-visualisation-of-qrack-output](https://github.com/twobombs/thereminq-bonsai#deploy-bonsai-visualisation-of-qrack-output)
